
MAX_HONEY <- 25
MAX_POLLEN <- 12
MAX_BROOD <- 21

QUEEN_CELLS_PER_HOUR <- 60

BROOD_RADIUS <- 4

TOTAL_DAILY_HONEY <- 2000 #833

POLLEN_RATIO <- 0.21

POLLEN_CONSUMPTION_RATIO <- 0.99
HONEY_CONSUMPTION_RATIO <- 0.59

#Only collecting during the day
HONEY_BY_HOUR <- ceiling(TOTAL_DAILY_HONEY/12)
POLLEN_BY_HOUR <- ceiling((TOTAL_DAILY_HONEY*POLLEN_RATIO)/12)


