
MAX_HONEY <- 25
MAX_POLLEN <- 12
MAX_BROOD <- 21

QUEEN_CELLS_PER_HOUR <- 60 / 4

TOTAL_DAILY_HONEY <- 833

POLLEN_RATIO <- 0.21

POLLEN_CONSUMPTION_RATIO <- 0.99
HONEY_CONSUMPTION_RATIO <- 0.59

BROOD_POLLEN_CONSUMPTION_RATIO <- 0.99
BROOD_HONEY_CONSUMPTION_RATIO <- 0.33

N_BEES <- 30
N_NURSES <- 30

#Only collecting during the day, eat all the time (Night and day coming later, all 12 for now)
HONEY_BY_HOUR_BY_BEE <- ceiling(TOTAL_DAILY_HONEY/N_BEES/12)
POLLEN_BY_HOUR_BY_BEE <- ceiling((TOTAL_DAILY_HONEY*POLLEN_RATIO)/N_BEES/12)

EATEN_HONEY_BY_HOUR_BY_BEE <- ceiling((TOTAL_DAILY_HONEY*HONEY_CONSUMPTION_RATIO)/N_BEES/12)
EATEN_POLLEN_BY_HOUR_BY_BEE <- ceiling((TOTAL_DAILY_HONEY*POLLEN_RATIO*POLLEN_CONSUMPTION_RATIO)/N_BEES/12)

BROOD_EATEN_HONEY_BY_HOUR_BY_BEE <- ceiling((TOTAL_DAILY_HONEY*BROOD_HONEY_CONSUMPTION_RATIO)/N_NURSES/12)
BROOD_EATEN_POLLEN_BY_HOUR_BY_BEE <- ceiling((TOTAL_DAILY_HONEY*POLLEN_RATIO*BROOD_POLLEN_CONSUMPTION_RATIO)/N_NURSES/12)

BROOD_HONEY_NEEDED <- 1
BROOD_POLLEN_NEEDED <- 2

