---
title: "Hive Parameter Analysis"
output: html_notebook
---

```{r Load Packages}
library(tidyverse)
library(ggplot2)
library(readr)
```

```{r Read in Data}

bee_param_df <- list.files(path="hive_data/heat_queen/", full.names = TRUE) %>% 
                lapply(read_csv, show_col_types = FALSE) %>% 
                bind_rows

write.csv(bee_param_df,"bee_data_isaac_heat_queen.csv",row.names = FALSE)

```

What these all mean:
n = queen cells per hour
rb = brood radius
rn = necter radius
w = total daily honey
pph = pollen ratio
ph = honey consumption ratio
pp = pollen consumption ratio
k = consumption probability value

broodMetric = average number of brood surrounding other brood
pollenRing = average min distance between honey and brood

```{r}
brood_bee_param <- read.csv("bee_data_isaac_heat_brood.csv") %>% mutate(type = "Brood")
worker_bee_param <- read.csv("bee_data_isaac_heat_worker.csv") %>% mutate(type = "Worker")
queen_bee_param <- read.csv("bee_data_isaac_heat_queen.csv") %>% mutate(type = "Queen")

bee_heat_param_df <- rbind(brood_bee_param,worker_bee_param) %>% rbind(.,queen_bee_param)
```


```{r}
ggplot(bee_heat_param_df, aes(x = type, y = pBroodHeat))+
  geom_boxplot()+
  theme_classic()

heat_glm <- glm(pBroodHeat ~ 0 + type, data = bee_heat_param_df)
heat_glm
```


```{r}
rand_bee_param <- read.csv("bee_data_isaac_rand.csv") %>% mutate(type = "Rand")
m1_bee_param <- read.csv("bee_data_isaac_m1.csv") %>% mutate(type = "M1") %>% select(-trial_n)
m2_bee_param <- read.csv("bee_data_isaac_m2.csv") %>% mutate(type = "M2") %>% select(-trial_n)
m2E_bee_param <- read.csv("bee_data_isaac_m2_empty.csv") %>% mutate(type = "M2E") %>% select(-trial_n)
m2K_bee_param <- read.csv("bee_data_isaac_m2_katie.csv") %>% mutate(type = "M2K") %>% select(-trial_n)

bee_param_df <- rbind(m1_bee_param,m2_bee_param) %>% rbind(.,rand_bee_param) %>% rbind(.,m2E_bee_param) %>% rbind(.,m2K_bee_param)
```


```{r}
bee_param_df_perc <- bee_param_df %>% select(c(type,pBrood,pHoney,pPollen,pEmpty)) %>%
                                      pivot_longer(c(pBrood,pHoney,pPollen,pEmpty))
```


```{r Overall Brood and Pollen}

ggplot(bee_param_df, aes(x = broodMetric, y = pollenRing, color = type))+
  geom_point(alpha = 0.25)+
  ylim(0,16)+
  xlim(0,6)+
  theme_classic()

ggplot(bee_param_df_perc, aes(x = type, y = value, fill = name))+
  geom_boxplot()+
  theme_classic()

ggplot(m1_bee_param, aes(x = pPollen, y = pph))+
  geom_point()+
  theme_classic()

```

```{r Brood Metric GLMs}
broodMetricGLM_m0 <- glm(broodMetric ~ 1, data = m2_bee_param)
broodMetricGLM_m1 <- glm(broodMetric ~ n + rb + rn + w + pph + ph + pp + k, data = m2_bee_param)
broodMetricGLM_step <- step(broodMetricGLM_m0, direction = "both", scope = formula(broodMetricGLM_m1), trace = 0)

summary(broodMetricGLM_step)
```

```{r Pollen Ring GLMs}
pollenRingGLM_m0 <- glm(pollenRing ~ 1, data = m2_bee_param)
pollenRingGLM_m1 <- glm(pollenRing ~ n + rb + rn + w + pph + ph + pp + k, data = m2_bee_param)
pollenRingGLM_step <- step(pollenRingGLM_m0, direction = "both", scope = formula(pollenRingGLM_m1), trace = 0)

summary(pollenRingGLM_step)
```


